atomresponder/urls.py
from django.urls import path,re_path
from .views import JobNotifyView, ImportJobListView #, ResyncToAtomApi
# This new app handles the request to the URL by responding with the view which is loaded
# from portal.plugins.gnmkinesisresponder.views.py. Inside that file is a class which responsedxs to the
# request, and sends in the arguments template - the html file to view.
# name is shortcut name for the urls.

urlpatterns = [
   path(r'jobnotify', JobNotifyView.as_view(), name='import_notification'),
   path(r'admin/jobs', ImportJobListView.as_view(), name='job_list'),
   #re_path(r'^resync/(?P<item_id>\w{2}-\d+)$', ResyncToAtomApi.as_view(), name='resync_to_atom')
]

urls.py
from django.urls import path, include

urlpatterns = [
    path('kinesis/', include('kinesisresponder.urls')),
    path('atomresponder/', include('atomresponder.urls'))
]

atomresponder/models.py
from django.db import models

#technically this does not belong here but it needs to be called late in every init, in order to register signals but import
#from other modules' .tasks
from .signals import *
#setup_signals()


class ImportJob(models.Model):
    item_id = models.CharField(max_length=64, db_index=True)
    job_id = models.CharField(max_length=64, db_index=True, unique=True)
    atom_id = models.CharField(max_length=64,db_index=True)
    status = models.CharField(max_length=64, choices=[
        ('READY', 'Ready'),
        ('STARTED','Started'),
        ('FINISHED','Success'),
        ('FINISHED_WARNING','Non-fatal error'),
        ('FAILED_TOTAL','Failed'),
        ('WAITING', 'Waiting'),
        ('ABORT_PENDING', 'Abort requested'),
        ('ABORTED', 'Cancelled by admin')
    ])
    atom_title = models.CharField(max_length=1024, default="Unknown title")
    user_email = models.CharField(max_length=1024, default="Unknown user", db_index=True)
    started_at = models.DateTimeField()
    completed_at = models.DateTimeField(null=True)
    s3_path = models.CharField(max_length=2048, null=True)
    retry_number = models.IntegerField(default=0)
    processing = models.BooleanField(default=False)

    class Meta:
        ordering = ['-started_at']

    def is_failed(self):
        """
        Returns a boolean indicating whether the status of this job represents any kind of failure
        :return:
        """
        if self.status=='FAILED_TOTAL' or self.status=='FINISHED_WARNING' or self.status=='ABORTED':
            return True
        else:
            return False

    def previous_attempt(self):
        """
        Either returns the job reference of the previous attempt of this import, or None
        :return: an ImportJob instance or None
        """
        for entry in ImportJob.objects.filter(atom_id=self.atom_id).order_by('-retry_number')[:1]:
            return entry
        return None

    def __str__(self):
        return "Import of {0} from {1} to item {2}".format(self.atom_title, self.user_email, self.item_id)


class PacFormXml(models.Model):
    atom_id = models.CharField(max_length=64, db_index=True, unique=True)
    received = models.DateTimeField()
    completed = models.DateTimeField(blank=True, null=True)
    pacdata_url = models.CharField(max_length=4096)
    status = models.CharField(max_length=32, choices=[
        ("UNPROCESSED", "Unprocessed"),
        ("DOWNLOADING", "Downloading"),
        ("INPROGRESS", "In progress"),
        ("PROCESSED", "Processed"),
        ("ERROR", "Error")
    ], default="UNPROCESSED",db_index=True)
    celery_task_id = models.CharField(max_length=64, db_index=True, null=True)
    last_error = models.TextField(blank=True)

atomresponder/views.py
from rest_framework.views import APIView
from rest_framework.renderers import JSONRenderer
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from django.views.generic.list import ListView
import logging

logger = logging.getLogger(__name__)


class JobNotifyView(APIView):
    permission_classes = (AllowAny, )
    renderer_classes = (JSONRenderer, )

    def post(self, request):
        """
        Receives notifications from VS that a relevant import has taken place.
        Notification is set up in notification.py
        :param request: Django request object
        :return: Response
        """
        from rabbitmq.job_notification import JobNotification
        from lxml.etree import XMLSyntaxError, LxmlError
        from .notification import process_notification
        from .models import ImportJob

        logger.info("Received import notification")
        try:
            notification = JobNotification(request.body)
        except XMLSyntaxError:
            logger.error("Invalid XML document received from Vidispine: {0}".format(request.body))
            return Response({'status': 'Bad XML'}, status=400) #returning 400=> VS won't try again
        except LxmlError:
            logger.error("Unable to process Vidispine XML document, but syntax as ok")
            return Response({'status': 'Unable to process'}, status=500) #returning 500=> VS will try again (more likely problem is our side)

        try:
            process_notification(notification)
            return Response({'status': 'ok'})
        except ImportJob.DoesNotExist:
            logger.error("JobNotifyView: No import job found for {0}".format(notification))
            return Response({'status': 'notfound'}, status=200)


class ImportJobListView(ListView):
    from .models import ImportJob
    model = ImportJob

    template_name = "gnmatomresponder/import_job_list.html"

    def get_queryset(self):
        qs = self.model.objects.all()

        if 'status' in self.request.GET:
            qs = qs.filter(status=self.request.GET['status'])
        if 'itemId' in self.request.GET and self.request.GET['itemId']!='':
            qs = qs.filter(item_id=self.request.GET['itemId'])

        return qs.order_by('-completed_at', '-started_at')

    def get_context_data(self, **kwargs):
        rtn = super(ImportJobListView, self).get_context_data(**kwargs)
        if 'intest' in self.request.GET:
            rtn['in_test'] = True
        else:
            rtn['in_test'] = False
        return rtn


# class ResyncToAtomApi(APIView):
#     renderer_classes = (JSONRenderer, )
#
#     def get(self, request, item_id=None):
#         from portal.plugins.gnm_masters.models import VSMaster
#         import portal.plugins.gnm_vidispine_utils.constants as const
#         import requests
#         from django.conf import settings
#
#         try:
#             master = VSMaster(item_id, request.user)
#             atom_id = master.get(const.GNM_MASTERS_MEDIAATOM_ATOMID, "")
#
#             if atom_id is None:
#                 return Response({"status": "error","error": "This master has no atom ID yet"}, status=400)
#
#             url = settings.GNM_ATOM_RESPONDER_LAUNCHDETECTOR_URL + "/update/" + atom_id
#             logger.info("Update URL for {0} is {1}".format(item_id, url))
#             response = requests.put(url)
#
#             logger.info("Updating {0}: Launch detector said {1} {2}".format(item_id, response.status_code, response.content))
#             #simply echo the Launch Detector's response back to the client
#             return Response(response.json(), status=response.status_code)
#         except requests.ConnectTimeout:
#             return Response({"status": "error", "error": "Timeout connecting to LaunchDetector, please try again and notify multimediatech@theguardian.com"},status=500)
#         except requests.ConnectionError:
#             return Response({"status": "error", "error": "Unable to connect to LaunchDetector, please notify multimediatech@theguardian.com"},status=500)
#         except Exception as e:
#             return Response({"status": "error", "error": str(e)},status=500)

atomresponder/templates/gnmatomresponder/import_job_list.html
{% themeextends "admin/base_admin.html" %}
{% load i18n datetimeformatting compress staticfiles %}
{% block title %}{% trans 'Media atom import jobs' %}{% endblock %}
{% block heading %}{% trans 'Media atom import jobs' %}{% endblock %}

{% block extra_script %}

{% endblock %}

{% block content %}
    <form method="GET">
    <table>
        <tr>
            <td width="20%"><label for="id_itemId">Item ID</label></td>
            <td width="20%"><input type="text" name="itemId" id="id_itemId"></td>
        </tr>
        <tr>
            <td><label for="id_status">Job status</label></td>
            <td>
                <select name="status" id="id_status">
                    <option name="FAILED_TOTAL">FAILED_TOTAL</option>
                    <option name="FINISHED_WARNING">FINISHED_WARNING</option>
                    <option name="STARTED">STARTED</option>
                </select>
            </td>
        </tr>
    </table>
    <input type="submit" value="Search">
    </form>

<table>
    <thead>
        <tr>
            <td>Item ID</td>
            <td>Job ID</td>
            <td>Status</td>
            <td>Started</td>
            <td>Completed</td>
        </tr>
    </thead>
    <tbody>
    {% for jobinfo in object_list %}
        <tr>
            <td><a href="/vs/item/{{ jobinfo.item_id }}">{{ jobinfo.item_id }}</a></td>
            <td><a href="/vs/job/{{ jobinfo.job_id }}">{{ jobinfo.job_id }}</a></td>
            <td>{{ jobinfo.status }}</td>
            <td>{{ jobinfo.started_at }}</td>
            <td>{{ jobinfo.completed_at }}</td>
        </tr>
    {% empty %}
        <tr>
            <td>No jobs yet!</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

atomresponder/templates/gnmatomresponder/navigation.html
{% load i18n staticfiles %}
<li>
    <!--<span class="iicon" style="background-image: url('{% static 'purgemeister/target_icon.png' %}');"></span>-->
    <img src="{% static 'gnmatomresponder/atomicon.png' %}" class="iicon" style="background: none">
    <a href="{% url gnmatomresponder:job_list %}">Atom Imports</a>
</li>

atomresponder/templates/gnmatomresponder/resync_widget.html
{% load static %}

<div id="atom-resync-widget" style="display:none;">
    <span id="rescan-throbber" style="display: none;"><img src="{% static 'img/icon-ajax-loader.gif' %}">Resyncing...</span>
    <button id="resync-button" type="button" onClick="startResync();">Resync to published data</button>
    <span id="rescan-complete-message" style="display: none">Resync has completed, this may take a few minutes to show</span>
    <span id="rescan-failed-messsage" class="error" style="display: none">Resync request was rejected, try again later and contact multimediatech@theguardian.com</span>
</div>

<script>
    function startResync(){
        $('#resync-button').hide();
        $('#rescan-throbber').show();
        $.ajax("{% url gnmatomresponder:resync_to_atom item_id=master.id %}")
            .done(function(data, textStatus, jqXHR){
                console.log(data);
                $('#rescan-throbber').hide();
                $('#resync-complete-message').show();
            })
            .fail(function(jqXHR, textStatus, errorThrown){
                $('#rescan-throbber').hide();
                try {
                    var jsonData = JSON.parse(jqXHR.responseText);
                    console.error(jsonData);
                    var errorMsg;
                    if(jsonData.hasOwnProperty("detail")){
                        errorMsg = jsonData.detail;
                    } else if (jsonData.hasOwnProperty("error")){
                        errorMsg = jsonData.error;
                    } else {
                        errorMsg = jqXHR.responseText;
                    }
                    $('#rescan-failed-messsage').text("Resync request was rejected: " + errorMsg).show();
                } catch(e) {
                    console.error("Could not parse server response", e);
                    $('#rescan-failed-messsage').show();
                }
            });
    }
    $(document).ready(function(){
        //only show the atom resync button if it's going to work
        if($('#id_gnm_master_mediaatom_atomid').val()!=="") $('#atom-resync-widget').show();
    })
</script>